# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rasactl < Formula
  desc "rasactl deploys Rasa X / Enterprise on your local or remote Kubernetes cluster and manages Rasa X / Enterprise deployments."
  homepage "https://github.com/RasaHQ/rasactl"
  version "0.0.11"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.11/rasactl_0.0.11_darwin_amd64.tar.gz"
      sha256 "3026411041eeff4fec7dd33265eb285829ab18021ae55c9e7fe4cc6412040e1c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.11/rasactl_0.0.11_darwin_arm64.tar.gz"
      sha256 "70ad0979c165f278f44d807efd5e09a77c2deb318ec8b11c8462d4c0e9194559"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.11/rasactl_0.0.11_linux_amd64.tar.gz"
      sha256 "0547c64f98c33fa593021707d1ade93cdbc92f8171fe4c790a76fd8be5f44a23"
    end
  end

  def install
    bin.install "rasactl"
    bash_completion.install "completions/goreleaser.bash" => "rasactl"
    zsh_completion.install "completions/goreleaser.zsh" => "_rasactl"
    fish_completion.install "completions/goreleaser.fish"
  end

  test do
    system "#{bin}/rasactl --version"
  end
end
