# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rasactl < Formula
  desc "rasactl deploys Rasa X / Enterprise on your local or remote Kubernetes cluster and manages Rasa X / Enterprise deployments."
  homepage "https://github.com/RasaHQ/rasactl"
  version "0.0.23"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.23/rasactl_0.0.23_darwin_amd64.tar.gz"
      sha256 "6dc2eb3e0383c1dd52eb9e8f3bd56a02143ce439f0e39a07d0430a77f4de1f49"
    end
    if Hardware::CPU.arm?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.23/rasactl_0.0.23_darwin_arm64.tar.gz"
      sha256 "28bcc2d9a156fcf83eaee21d3d04636d8f9ddf74cbfa22c134ba04b71a97b17f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.0.23/rasactl_0.0.23_linux_amd64.tar.gz"
      sha256 "58b99383698d5d14c55a9d377da51368eb5e2410e9a97b3ce699072e46b7d56f"
    end
  end

  def install
    bin.install "rasactl"
    bash_completion.install "completions/rasactl.bash" => "rasactl"
    zsh_completion.install "completions/rasactl.zsh" => "_rasactl"
    fish_completion.install "completions/rasactl.fish"
  end

  test do
    system "#{bin}/rasactl --version"
  end
end
