# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rasactl < Formula
  desc "rasactl deploys Rasa X / Enterprise on your local or remote Kubernetes cluster and manages Rasa X / Enterprise deployments."
  homepage "https://github.com/RasaHQ/rasactl"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.4.2/rasactl_0.4.2_darwin_amd64.tar.gz"
      sha256 "9885cdc15cc9a6f74c7fb86da912aef16ad9d028e887fb72349b6eddb532ea1b"

      def install
        bin.install "rasactl"
        bash_completion.install "completions/rasactl.bash" => "rasactl"
        zsh_completion.install "completions/rasactl.zsh" => "_rasactl"
        fish_completion.install "completions/rasactl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.4.2/rasactl_0.4.2_darwin_arm64.tar.gz"
      sha256 "1eb39a2b1354a66811b2b95888617634795f7ec1909a76a8f6e6317b63717b33"

      def install
        bin.install "rasactl"
        bash_completion.install "completions/rasactl.bash" => "rasactl"
        zsh_completion.install "completions/rasactl.zsh" => "_rasactl"
        fish_completion.install "completions/rasactl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RasaHQ/rasactl/releases/download/0.4.2/rasactl_0.4.2_linux_amd64.tar.gz"
      sha256 "562b97bd6a3c00154c59d92a67ad1ba5d3c341a76d80b99ef95b9fdc085a97e2"

      def install
        bin.install "rasactl"
        bash_completion.install "completions/rasactl.bash" => "rasactl"
        zsh_completion.install "completions/rasactl.zsh" => "_rasactl"
        fish_completion.install "completions/rasactl.fish"
      end
    end
  end

  test do
    system "#{bin}/rasactl --version"
  end
end
